#### REGION ANNOTATIONS ####
  #### subregion annotations ####
    #### Ctrl Regions ####
    Ctrl_MedRes_point_ids <- list(1:100,1:105,1:70)
    Ctrl_MedRes_subregions <- list(c('Alveus',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'Alveus',
                                     'Alveus',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Alveus',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'Au',
                                     'Au',
                                     'Au',
                                     'Alveus',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'SRL',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'Alveus',
                                     'Au',
                                     'Alveus',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'ML',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC'),
                                   c('EC',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'ML',
                                     'DG',
                                     'DG',
                                     'SRL',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'Alveus',
                                     'Alveus',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'DG',
                                     'DG',
                                     'DG',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'DG',
                                     'CA4',
                                     'DG',
                                     'DG',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'Alveus',
                                     'Alveus',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'DG',
                                     'CA4',
                                     'CA4',
                                     'CA4',
                                     'DG',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'DG',
                                     'CA4',
                                     'CA4',
                                     'CA4',
                                     'DG',
                                     'SRL',
                                     'CA1',
                                     'Alveus',
                                     'Au',
                                     'Au',
                                     'Alveus',
                                     'CA2',
                                     'SRL',
                                     'SRL',
                                     'CA4',
                                     'CA4',
                                     'CA4',
                                     'DG',
                                     'ML',
                                     'SRL',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'DG',
                                     'CA4',
                                     'CA4',
                                     'CA3',
                                     'CA3',
                                     'CA2',
                                     'CA2',
                                     'Alveus',
                                     'Au'),
                                   c('Au',
                                     'Alveus',
                                     'CA3',
                                     'CA3',
                                     'CA3',
                                     'CA4',
                                     'CA4',
                                     'DG',
                                     'ML',
                                     'SRL',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'EC',
                                     'EC',
                                     'CA1',
                                     'CA1',
                                     'CA1',
                                     'SRL',
                                     'ML',
                                     'DG',
                                     'CA4',
                                     'CA4',
                                     'CA3',
                                     'Alveus',
                                     'Alveus',
                                     'Au',
                                     'Au',
                                     'Alveus',
                                     'Alveus',
                                     'DG',
                                     'DG',
                                     'DG',
                                     'ML',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'Subiculum',
                                     'SRL',
                                     'DG',
                                     'DG',
                                     'Fimbria',
                                     'Fimbria',
                                     'Au',
                                     'Fimbria',
                                     'Fimbria',
                                     'TH-LV',
                                     'TH-LV',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'PreSubiculum',
                                     'TH-LV',
                                     'Fimbria',
                                     'Fimbria',
                                     'Au'))
    #### MedAD Regions ####
    MedAD_MedRes_point_ids <- list(1:260)
    MedAD_MedRes_subregions <- list('Au',
                                    'Au',
                                    'Au',
                                    'Alveus',
                                    'Alveus',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'Alveus',
                                    'Alveus',
                                    'Alveus',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'SRL',
                                    'SRL',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'SRL',
                                    'ML',
                                    'ML',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'Alveus',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'EC',
                                    'Alveus',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'DG',
                                    'DG',
                                    'SRL',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'Alveus',
                                    'EC',
                                    'EC',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'DG',
                                    'DG',
                                    'CA4',
                                    'DG',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'DG',
                                    'DG',
                                    'CA4',
                                    'DG',
                                    'DG',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Alveus',
                                    'Alveus',
                                    'Alveus',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'SRL',
                                    'DG',
                                    'CA4',
                                    'CA4',
                                    'CA4',
                                    'CA2',
                                    'CA2',
                                    'Alveus',
                                    'Au',
                                    'Au',
                                    'Alveus',
                                    'CA2',
                                    'CA2',
                                    'CA3',
                                    'CA4',
                                    'CA4',
                                    'DG',
                                    'ML',
                                    'SRL',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'SRL',
                                    'DG',
                                    'DG',
                                    'CA4',
                                    'CA4',
                                    'CA3',
                                    'CA2',
                                    'CA2',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Alveus',
                                    'Alveus',
                                    'CA3',
                                    'CA4',
                                    'CA4',
                                    'CA4',
                                    'DG',
                                    'DG',
                                    'CA1',
                                    'CA1',
                                    'CA1',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'Alveus',
                                    'Alveus',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Alveus',
                                    'Alveus',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'DG',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'ML',
                                    'ML',
                                    'ML',
                                    'Fimbria',
                                    'Fimbria',
                                    'Fimbria',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Fimbria',
                                    'Fimbria',
                                    'Fimbria',
                                    'Fimbria',
                                    'TH-LV',
                                    'TH-LV',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'Subiculum',
                                    'PreSubiculum',
                                    'PreSubiculum',
                                    'PreSubiculum',
                                    'PreSubiculum',
                                    'TH-LV',
                                    'TH-LV',
                                    'TH-LV',
                                    'Fimbria',
                                    'Fimbria',
                                    'Au',
                                    'Au',
                                    'Au',
                                    'Au')
    #### HiAD Regions ####
    HiAD_MedRes_point_ids <- list(1:196)
    HiAD_MedRes_subregions <- list('Au',
                                   'Alveus',
                                   'Fimbria',
                                   'Fimbria',
                                   'Fimbria',
                                   'DG',
                                   'DG',
                                   'ML',
                                   'Au',
                                   'SRL',
                                   'PreSubiculum',
                                   'EC',
                                   'PreSubiculum',
                                   'PreSubiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'SRL',
                                   'SRL',
                                   'ML',
                                   'DG',
                                   'DG',
                                   'DG',
                                   'Fimbria',
                                   'Alveus',
                                   'Alveus',
                                   'Alveus',
                                   'Au',
                                   'Au',
                                   'Alveus',
                                   'Alveus',
                                   'CA3',
                                   'CA3',
                                   'CA3',
                                   'CA4',
                                   'DG',
                                   'DG',
                                   'SRL',
                                   'SRL',
                                   'Subiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'Subiculum',
                                   'SRL',
                                   'SRL',
                                   'DG',
                                   'DG',
                                   'CA4',
                                   'CA4',
                                   'CA3',
                                   'CA3',
                                   'CA3',
                                   'Alveus',
                                   'Alveus',
                                   'Alveus',
                                   'CA2',
                                   'CA3',
                                   'CA3',
                                   'CA4',
                                   'CA4',
                                   'CA4',
                                   'DG',
                                   'DG',
                                   'SRL',
                                   'SRL',
                                   'Subiculum',
                                   'Subiculum',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'SRL',
                                   'SRL',
                                   'DG',
                                   'DG',
                                   'CA4',
                                   'CA4',
                                   'CA4',
                                   'DG',
                                   'CA2',
                                   'CA2',
                                   'Alveus',
                                   'Alveus',
                                   'CA2',
                                   'CA2',
                                   'DG',
                                   'CA4',
                                   'CA4',
                                   'DG',
                                   'DG',
                                   'ML',
                                   'SRL',
                                   'SRL',
                                   'CA1',
                                   'CA1',
                                   'EC',
                                   'EC',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'SRL',
                                   'ML',
                                   'DG',
                                   'DG',
                                   'DG',
                                   'DG',
                                   'DG',
                                   'CA2',
                                   'CA2',
                                   'Alveus',
                                   'Alveus',
                                   'CA1',
                                   'CA1',
                                   'ML',
                                   'ML',
                                   'DG',
                                   'DG',
                                   'DG',
                                   'ML',
                                   'SRL',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'CA1',
                                   'CA1',
                                   'SRL',
                                   'SRL',
                                   'DG',
                                   'ML',
                                   'ML',
                                   'SRL',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'Alveus',
                                   'Au',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'SRL',
                                   'SRL',
                                   'SRL',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'Alveus',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'Alveus',
                                   'Au',
                                   'Au',
                                   'Alveus',
                                   'Alveus',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'Alveus',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'EC',
                                   'Alveus',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'CA1',
                                   'Alveus',
                                   'Au',
                                   'Au',
                                   'Au')
    #### add annotations to datasets ####
    ## use to reset ##
    master_data_Med$Subregions <- NULL
    master_data_Ctrl$Subregions <- NULL
    master_data_Hi$Subregions <- NULL
    ## ##
    master_data_Ctrl <- arrange(master_data_Ctrl, run_type_id, point_id)
    Ctrl_annotations <- list('point' = Ctrl_MedRes_point_ids, 'annotations' = Ctrl_MedRes_subregions)
    run_names_Ctrl <- c('Ctrl1', 'Ctrl2', 'Ctrl3')
    Subregions <- c()
    for (i in 1:3) {
      current_points <- Ctrl_annotations$point[[i]]
      current_run <- run_names_Ctrl[i]
      for (j in current_points) {
        subregion_temp <- Ctrl_annotations$annotations[[i]][j]
        obj_length_temp <- dim(filter(master_data_Ctrl, run_type_id == current_run & point_id == j))[1]
        subregion_vector_temp <- rep(subregion_temp, obj_length_temp)
        Subregions <- c(Subregions, subregion_vector_temp)
      }
    }
    master_data_Ctrl <- cbind(master_data_Ctrl, Subregions)
    
    # need to double check 0 indexing in points in data vs points in excel sheet for med Res
    master_data_Med <- arrange(master_data_Med, point_id)
    MedAD_annotations <- list('point' = MedAD_MedRes_point_ids, 'annotations' = MedAD_MedRes_subregions)
    Subregions <- c()
    for (i in 1:length(MedAD_annotations$annotations)) {
      subregion_temp <- MedAD_annotations$annotations[[i]]
      obj_length_temp <- dim(filter(master_data_Med, point_id == i-1))[1]
      subregion_vector_temp <- rep(subregion_temp, obj_length_temp)
      Subregions <- c(Subregions, subregion_vector_temp)
    }
    master_data_Med <- cbind(master_data_Med, Subregions)
    
    # add annotations to datasets
    master_data_Hi <- arrange(master_data_Hi, point_id)
    HiAD_annotations <- list('point' = HiAD_MedRes_point_ids, 'annotations' = HiAD_MedRes_subregions)
    Subregions <- c()
    for (i in 1:length(HiAD_annotations$annotations)) {
      subregion_temp <- HiAD_annotations$annotations[[i]]
      obj_length_temp <- dim(filter(master_data_Hi, point_id == i))[1]
      subregion_vector_temp <- rep(subregion_temp, obj_length_temp)
      Subregions <- c(Subregions, subregion_vector_temp)
    }
    master_data_Hi <- cbind(master_data_Hi, Subregions)
    
    all_annotations <- c(Ctrl_annotations, MedAD_annotations, HiAD_annotations)
    levels(master_data_Ctrl$Subregions)
    levels(master_data_Med$Subregions)
    levels(master_data_Hi$Subregions)




#### PRE-TILING #####
  # create a unique RGB identifier for every object + cell in master_data
  # master_data_all and master_data_all_log1
  n_objects <- dim(master_data)[1]
  nRGB_ids <- matrix(nrow = n_objects, ncol = 4)
  
  for (num in 1:n_objects) {
    nRGB_ids[num, 1] <- num
    B = num %% 256
    G = ((num-B) / 256) %% 256
    R = ((num-B) / 256**2) - (G/256)
    nRGB_ids[num, 2:4] <- c(R,G,B)
  }
  # attach RGB_ids to master_data, renaming columns
  master_data_all <- cbind(master_data, nRGB_ids)
  master_data_all_cuberoot <- cbind(master_data_all_cuberoot, nRGB_ids)
  setnames(master_data_all, old = c('1','2','3','4'), new = c('spatial_id','R','G','B'))
  setnames(master_data_all_log1, old = c('1','2','3','4'), new = c('spatial_id','R','G','B'))
  # can now move to object_image_writer with for_tiling == T, clustering turned off

#### POST-TILING #####
  # connect back tiled data overlay spatial properties. - Do for Hi, Med, Ctrl
  # extract unique id, property information
  obj_type_id_tiled = c('cells', 'vessels', 'microglia-processes', 'amyloid-pathies', 'tau-pathies')
  data_paths =  c('/Volumes/BryJC_Stanford/Data/Cleaned_Data_Kausi/MedRes_HiADCase/NoAuBGFFtDenoised_New/obj_images/ez1dc1/HiAD/unique_ids/TILING/',
                '/Volumes/BryJC_Stanford/Data/Cleaned_Data_Kausi/MedRes_MedADCase/NoAuBGFFtDenoised_New/obj_images/ez1dc1/MedAD/unique_ids/TILING/',
                '/Volumes/BryJC_Stanford/Data/Cleaned_Data_Kausi/MedRes_ControlCase/obj_images/ez1dc1/TILING/')
  spatial_data_all = data.frame()
  
  for (spatial_file in data_paths) {
    for (obj in obj_type_id_tiled) {
      obj_path <- paste0(spatial_file, obj, '_tiled_properties.mat')
      obj_mat <- readMat(obj_path, fixNames = FALSE) # read in .mat file generated from Matlab
      obj_df <- data.frame(matrix(unlist(obj_mat), ncol = length(obj_mat))) # flatten list with each column representing the obj properties, turn into a data frame by way of matrix
      setnames(obj_df, names(obj_mat)) # add back names of properties in
      # use left_join --> return all rows from master_data, and all columns from master_data and tiled_properties. Rows in master_data with no match in tiled_properties y spatial_id will have NA values in the new columns.
      spatial_data_all <- rbind(spatial_data_all, obj_df)
    }
  }

  # export to csv for Matlab use after all spatial information for Hi, Med, Ctrl are attached to data.frame
  master_data_all_spatial <- full_join(master_data_all, spatial_data_all, by = 'spatial_id')
  write.csv(master_data, paste0(data_path,'master_data_Hi.csv'), row.names = FALSE)
# NOTE: need to figure out ow R does pass by reference and not pass by copy
  
#### OVERLAPPING OBJECTS IMPORT - CELL BASED #####
  #import csv for mapping (write later)
  #import gating mats, rename columns to spatial_id, tau_obj+, amyloid_obj+
  tau_obj_overlap <- read_csv('/Volumes/BryJC_Stanford/paper1_analysis/Fig6/overlap_gates/tau_overlapped_cells_gate.csv',  col_names = FALSE)
  setnames(tau_obj_overlap, old = c('X1','X2'), new = c('spatial_id','tau_obj_POS'))
  
  amyloid_obj_overlap <- read_csv('/Volumes/BryJC_Stanford/paper1_analysis/Fig6/overlap_gates/amyloid_overlapped_cells_gate.csv',  col_names = FALSE)
  setnames(amyloid_obj_overlap, old = c('X1','X2'), new = c('spatial_id','amyloid_obj_POS'))
  
  #full join to data
  filter(master_regions_c, obj_type_id == 'cells') %>% left_join(tau_obj_overlap) %>% left_join(amyloid_obj_overlap) -> disease_cell_overlap
  disease_cell_overlap[is.na(disease_cell_overlap)] <- 0 #reset NA's to 0
  #factorize object positivity
  disease_cell_overlap$tau_obj_POS <- factor(disease_cell_overlap$tau_obj_POS)
  disease_cell_overlap$amyloid_obj_POS <- factor(disease_cell_overlap$amyloid_obj_POS)
  
#### OVERLAPPING OBJECTS IMPORT - DISEASE OBJECT BASED #####
  #import csv for mapping (write later)
  #import gating mats, rename columns to spatial_id, cell+
  cells_tau_obj_overlap <- read_csv('/Volumes/BryJC_Stanford/paper1_analysis/Fig6/overlap_gates/cells_overlapped_tau_gate.csv',  col_names = FALSE)
  setnames(cells_tau_obj_overlap, old = c('X1','X2'), new = c('spatial_id','cells_tau_obj_POS'))
  
  cells_amyloid_obj_overlap <- read_csv('/Volumes/BryJC_Stanford/paper1_analysis/Fig6/overlap_gates/cells_overlapped_amyloid_gate.csv',  col_names = FALSE)
  setnames(cells_amyloid_obj_overlap, old = c('X1','X2'), new = c('spatial_id','cells_amyloid_obj_POS'))
  
  #full join to data
  filter(master_regions_c, obj_type_id %in% c('tangles', 'plaques')) %>% left_join(cells_tau_obj_overlap) %>% left_join(cells_amyloid_obj_overlap) -> cell_disease_overlap
  cell_disease_overlap[is.na(cell_disease_overlap)] <- 0 #reset NA's to 0
  #factorize object positivity
  cell_disease_overlap$cells_tau_obj_POS <- factor(cell_disease_overlap$cells_tau_obj_POS)
  cell_disease_overlap$cells_amyloid_obj_POS <- factor(cell_disease_overlap$cells_amyloid_obj_POS)
  
  
#### EXPORT CENTROIDS, REGION CLASSES FOR VORONOI TESSELATIONS ####
  #for de novo regions
  for (run in c('Ctrl', 'MedAD', 'HiAD')) {
    voro_sample <- filter(master_regions_c, run_type_id == run) %>% select(X,Y,de_novo_regions,FlowSOM_ids,spatial_id)
    write_csv(voro_sample, paste0('/Volumes/BryJC_Stanford/other/ForDmitry/fig6_carpet_voronoi/', run, '_denovoregions_forVoronoi_expanded.csv'))
  }
  #for anat_id
  for (run in c('Ctrl', 'MedAD', 'HiAD')) {
    voro_sample <- filter(master_gated_anat2, run_type_id == run) %>% select(X,Y,anat_id,FlowSOM_ids,spatial_id)
    write_csv(voro_sample, paste0('/Volumes/BryJC_Stanford/other/ForDmitry/fig6_carpet_voronoi/', run, '_anat_forVoronoi_expanded.csv'))
  }